version: "3"
services:

  redis:
    image: redis:3.2
    ports:
      - "6379"
    networks:
      - frontend
    deploy:
      replicas: 1
    
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - 8000:80
    networks:
      - frontend
    depends_on:
      - redis
    deploy:
      replicas: 2

  result:
    image: bretfisher/examplevotingapp_result
    ports:
      - 5001:80
    networks:
      - backend
    depends_on:
      - db
    deploy:
      replicas: 1
   

  worker:
    image: bretfisher/examplevotingapp_worker:java
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - redis
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]


networks:
  frontend:
  backend:

volumes:
  db-data: